# AP0G33 kitty — Tokyo Night

font_family      JetBrains Mono
bold_font        auto
italic_font      auto
font_size        11.5

background_opacity      0.92
window_padding_width    8
cursor_shape            beam
enable_audio_bell       no
confirm_os_window_close 0
scrollback_lines        10000

# Tokyo Night
foreground #c0caf5
background #1a1b26
selection_foreground #16161e
selection_background #7aa2f7
cursor #c0caf5
cursor_text_color #1a1b26
url_color #7dcfff

active_tab_foreground   #16161e
active_tab_background   #7aa2f7
inactive_tab_foreground #565f89
inactive_tab_background #16161e

# black
color0 #15161e
color8 #414868
# red
color1 #f7768e
color9 #f7768e
# green
color2  #9ece6a
color10 #9ece6a
# yellow
color3  #e0af68
color11 #e0af68
# blue
color4  #7aa2f7
color12 #7aa2f7
# magenta
color5  #bb9af7
color13 #bb9af7
# cyan
color6  #7dcfff
color14 #7dcfff
# white
color7  #a9b1d6
color15 #c0caf5
